
/* 
  MOCK AI CONTROLLER 
  - Simulates LLM responses for reliability & demo purposes.
  - Can be replaced with actual OpenAI/Gemini calls.
*/

// Helper: Delay to simulate AI "thinking"
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export const generateTripPlan = async (req, res) => {
    const { destination, days, budget, type } = req.body;

    await delay(1500); // Simulate network/processing

    // Generic Templates
    const activities = {
        Beach: ["Relax at the beach", "Water sports", "Sunset cruise", "Seafood dinner"],
        Mountain: ["Hiking/Trekking", "Visit view points", "Bonfire night", "Local market"],
        City: ["City tour", "Museum visit", "Shopping", "Fine dining"],
        Spiritual: ["Temple visit", "Morning prayers", "Meditation", "Vegetarian meal"],
        Adventure: ["Bungee jumping", "Rafting", "Camping", "Climbing"]
    };

    // Determine type based on destination keyword if type not provided
    let selectedType = type || "City";
    const desc = destination.toLowerCase();

    if (desc.includes("goa") || desc.includes("maldives") || desc.includes("puri")) selectedType = "Beach";
    else if (desc.includes("manali") || desc.includes("shimla") || desc.includes("leh")) selectedType = "Mountain";
    else if (desc.includes("rishikesh")) selectedType = "Adventure";
    else if (desc.includes("kedarnath") || desc.includes("temp")) selectedType = "Spiritual";

    const acts = activities[selectedType] || activities["City"];
    const plan = [];

    for (let i = 1; i <= days; i++) {
        plan.push({
            day: i,
            title: `Day ${i}: ${selectedType} Exploration`,
            activities: [
                `Morning: ${acts[0]}`,
                `Afternoon: ${acts[1]}`,
                `Evening: ${acts[2]}`,
            ],
        });
    }

    res.status(200).json({
        success: true,
        data: {
            destination,
            days,
            type: selectedType,
            itinerary: plan,
            note: "Generated by AI Planner"
        }
    });
};

export const getWeatherSummary = async (req, res) => {
    const { location } = req.query;

    await delay(1000);

    // Mock Logic
    const month = new Date().getMonth();
    let weather = "Sunny & Pleasant";
    let temp = "25°C";

    const loc = location?.toLowerCase() || "";

    if (loc.includes("manali") || loc.includes("leh")) {
        if (month > 2 && month < 9) { weather = "Cool & Breezy"; temp = "15°C"; }
        else { weather = "Snowy & Cold"; temp = "-2°C"; }
    } else if (loc.includes("goa") || loc.includes("mumbai")) {
        if (month > 5 && month < 9) { weather = "Rainy (Monsoon)"; temp = "28°C"; }
        else { weather = "Sunny & Humid"; temp = "32°C"; }
    } else if (loc.includes("rajasthan") || loc.includes("jaipur")) {
        weather = "Hot & Sunny"; temp = "38°C";
    }

    const summary = `During your trip to ${location || "your destination"}, expect ${weather} (${temp}). Pack accordingly!`;

    res.status(200).json({
        success: true,
        data: {
            summary,
            temperature: temp,
            condition: weather
        }
    });
};

export const getPackingSuggestions = async (req, res) => {
    const { destination, days, type } = req.body;

    await delay(1200);

    const loc = destination?.toLowerCase() || "";
    const essentials = ["ID Proofs", "Phone Charger", "First Aid Kit", "Cash/Cards"];
    let clothes = ["T-shirts", "Jeans", "Comfortable Shoes"];
    let specific = [];

    if (loc.includes("manali") || loc.includes("snow") || type === "Mountain") {
        clothes = ["Thermals", "Heavy Jacket", "Woolen Socks", "Gloves"];
        specific = ["Snow Boots", "Moisturizer", "Sunglasses"];
    } else if (loc.includes("goa") || type === "Beach") {
        clothes = ["Shorts", "Swimwear", "Cotton Shirts", "Sandals"];
        specific = ["Sunscreen", "Hat/Cap", "Beach Towel"];
    } else if (type === "Adventure") {
        clothes = ["Track pants", "Dri-fit tees", "Trekking Shoes"];
        specific = ["Torch", "Power bank", "Bug spray"];
    }

    res.status(200).json({
        success: true,
        data: {
            categories: {
                Essentials: essentials,
                Clothing: clothes,
                "Weather Specific": specific
            }
        }
    });
};

export const chatWithAI = async (req, res) => {
    const { message } = req.body;

    await delay(1500);

    let response = "That's a great question! For detailed travel advice, I recommend checking our destination guides.";
    const msg = message?.toLowerCase() || "";

    if (msg.includes("pack")) response = "Packing depends on where you go! For beaches, pack light cottons. For mountains, bring layers and a good jacket.";
    else if (msg.includes("time") || msg.includes("when")) response = "Generally, October to March is the best time for most Indian destinations due to pleasant weather.";
    else if (msg.includes("budget") || msg.includes("cheap")) response = "For budget trips, consider places like Rishikesh, Pondicherry, or Gokarna depending on your location.";
    else if (msg.includes("hello") || msg.includes("hi")) response = "Hello! I am your AI Travel Assistant. How can I help you plan your next adventure?";

    res.status(200).json({
        success: true,
        data: {
            response
        }
    });
};
