import { useEffect, useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import api from "../api/axios";
import { motion, AnimatePresence } from "framer-motion";
import { 
    Briefcase, Plus, Trash2, Printer, RefreshCw, 
    RotateCcw, Check, Lock, ChevronDown, CheckCircle, 
    MapPin, Calendar, Users, ShieldAlert, Sparkles, Loader2
} from "lucide-react";
import { useNotification } from "../context/NotificationContext";

export default function PackingAssistant() {
    const navigate = useNavigate();
    const { success, error, info } = useNotification();
    const [searchParams, setSearchParams] = useSearchParams();
    const queryBookingId = searchParams.get("bookingId");

    // State variables
    const [bookings, setBookings] = useState([]);
    const [selectedBooking, setSelectedBooking] = useState(null);
    const [packingList, setPackingList] = useState([]);
    const [loadingBookings, setLoadingBookings] = useState(true);
    const [generatingList, setGeneratingList] = useState(false);
    const [saving, setSaving] = useState(false);
    const [newItemText, setNewItemText] = useState({});
    const [regenerateConfirm, setRegenerateConfirm] = useState(false);

    // Dynamic loading messages for AI generation
    const [loadingMessage, setLoadingMessage] = useState("Synchronizing travel coordinates...");

    const loadingMessages = [
        "Analyzing destination climate...",
        "Querying weather forecasts...",
        "Structuring packing categories...",
        "Tailoring checklist for your guests...",
        "Finalizing smart itinerary items...",
        "TripWell AI is polishing your checklist..."
    ];

    useEffect(() => {
        let msgIndex = 0;
        let interval;
        if (generatingList) {
            interval = setInterval(() => {
                msgIndex = (msgIndex + 1) % loadingMessages.length;
                setLoadingMessage(loadingMessages[msgIndex]);
            }, 2500);
        }
        return () => clearInterval(interval);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [generatingList]);

    // Fetch user bookings on mount
    useEffect(() => {
        fetchBookings();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const fetchBookings = async () => {
        try {
            const res = await api.get("/bookings/my");
            // Only confirmed/completed bookings can access the packing assistant
            const confirmedBookings = res.data.filter(
                b => b.status === "confirmed" || b.status === "completed"
            );
            setBookings(confirmedBookings);

            if (confirmedBookings.length > 0) {
                // If query parameter matches a confirmed booking, select it. Else select first one.
                const preselected = confirmedBookings.find(b => b._id === queryBookingId);
                if (preselected) {
                    setSelectedBooking(preselected);
                    loadPackingList(preselected._id);
                } else {
                    setSelectedBooking(confirmedBookings[0]);
                    loadPackingList(confirmedBookings[0]._id);
                    setSearchParams({ bookingId: confirmedBookings[0]._id });
                }
            }
        } catch (err) {
            console.error(err);
            error("Failed to load your bookings.");
        } finally {
            setLoadingBookings(false);
        }
    };

    // Load packing list for selected booking
    const loadPackingList = async (bookingId, forceRegenerate = false) => {
        setGeneratingList(true);
        try {
            const res = await api.post("/ai/packing", { 
                bookingId, 
                regenerate: forceRegenerate 
            });
            if (res.data.success) {
                setPackingList(res.data.data.packingList);
                if (forceRegenerate) {
                    success("Checklist successfully regenerated by AI!");
                }
            }
        } catch (err) {
            console.error(err);
            error(err.response?.data?.message || "Failed to generate packing suggestions.");
        } finally {
            setGeneratingList(false);
            setRegenerateConfirm(false);
        }
    };

    // Handle change in booking selection
    const handleBookingChange = (e) => {
        const bookingId = e.target.value;
        const booking = bookings.find(b => b._id === bookingId);
        if (booking) {
            setSelectedBooking(booking);
            setSearchParams({ bookingId });
            loadPackingList(bookingId);
        }
    };

    // Calculate total progress
    const totalItemsCount = packingList.reduce((acc, cat) => acc + cat.items.length, 0);
    const packedItemsCount = packingList.reduce(
        (acc, cat) => acc + cat.items.filter(item => item.packed).length, 0
    );
    const progressPercent = totalItemsCount > 0 ? Math.round((packedItemsCount / totalItemsCount) * 100) : 0;

    // Toggle item packed status
    const handleTogglePacked = async (categoryIndex, itemIndex) => {
        const updatedList = [...packingList];
        const item = updatedList[categoryIndex].items[itemIndex];
        item.packed = !item.packed;
        setPackingList(updatedList);
        saveChecklist(updatedList);
    };

    // Add a custom item to a category
    const handleAddItem = async (categoryIndex, categoryName) => {
        const text = newItemText[categoryName]?.trim();
        if (!text) return;

        const updatedList = [...packingList];
        updatedList[categoryIndex].items.push({
            name: text,
            packed: false,
            custom: true
        });

        setPackingList(updatedList);
        setNewItemText(prev => ({ ...prev, [categoryName]: "" }));
        saveChecklist(updatedList);
        success(`Added "${text}" to ${categoryName}`);
    };

    // Delete an item from a category
    const handleDeleteItem = async (categoryIndex, itemIndex, itemName) => {
        const updatedList = [...packingList];
        updatedList[categoryIndex].items.splice(itemIndex, 1);
        setPackingList(updatedList);
        saveChecklist(updatedList);
        info(`Removed "${itemName}"`);
    };

    // Reset checklist (uncheck all items)
    const handleResetChecklist = async () => {
        const updatedList = packingList.map(cat => ({
            ...cat,
            items: cat.items.map(item => ({ ...item, packed: false }))
        }));
        setPackingList(updatedList);
        saveChecklist(updatedList);
        info("Checklist reset! All items unmarked.");
    };

    // Persist checklist to backend
    const saveChecklist = async (listToSave) => {
        if (!selectedBooking) return;
        setSaving(true);
        try {
            await api.put(`/bookings/${selectedBooking._id}/packing`, {
                packingList: listToSave
            });
        } catch (err) {
            console.error(err);
            error("Failed to sync checklist changes with backend database.");
        } finally {
            setSaving(false);
        }
    };

    if (loadingBookings) {
        return (
            <div className="min-h-[80vh] flex flex-col items-center justify-center text-white">
                <Loader2 className="w-12 h-12 animate-spin text-indigo-500 mb-4" />
                <p className="text-gray-400 font-bold uppercase tracking-widest text-xs">Accessing packing logs...</p>
            </div>
        );
    }

    return (
        <div className="min-h-screen pt-6 px-4 md:px-8 pb-24 relative overflow-hidden print:bg-white print:text-black print:pt-0 print:pb-0">
            {/* BACKGROUND GLOWS (Hidden in Print) */}
            <div className="absolute top-0 left-1/4 w-96 h-96 bg-indigo-600/20 rounded-full blur-[120px] -z-10 print:hidden" />
            <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-[120px] -z-10 print:hidden" />

            <div className="max-w-6xl mx-auto relative z-10 print:max-w-full">
                {/* HEADER SECTION */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-6 print:mb-6">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="text-left"
                    >
                        <h1 className="text-3xl md:text-5xl font-black text-white uppercase tracking-tighter drop-shadow-2xl flex items-center gap-3 print:text-black print:text-3xl print:drop-shadow-none">
                            AI Packing Assistant <span className="text-indigo-400 print:hidden">🎒</span>
                        </h1>
                        <p className="mt-2 text-sm text-blue-100/50 font-medium tracking-tight max-w-lg print:text-gray-600 print:text-xs">
                            Personalized packing lists generated dynamically for your active confirmed expeditions.
                        </p>
                    </motion.div>

                    {/* SELECTOR dropdown - Hidden in print */}
                    {bookings.length > 0 && (
                        <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="flex items-center gap-3 bg-white p-3 rounded-2xl shadow-xl border border-gray-100 print:hidden"
                        >
                            <label className="text-indigo-950 font-black text-[10px] uppercase tracking-wider pl-2">Expedition:</label>
                            <div className="relative">
                                <select
                                    value={selectedBooking?._id || ""}
                                    onChange={handleBookingChange}
                                    className="bg-gray-50 border border-gray-100 text-indigo-950 font-black text-xs uppercase tracking-tight py-2.5 pl-4 pr-10 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer appearance-none"
                                >
                                    {bookings.map(b => (
                                        <option key={b._id} value={b._id}>
                                            {b.destination} ({new Date(b.startDate).toLocaleDateString()})
                                        </option>
                                    ))}
                                </select>
                                <ChevronDown size={14} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                            </div>
                        </motion.div>
                    )}
                </div>

                {/* NO BOOKINGS EMPTY STATE */}
                {bookings.length === 0 ? (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="text-center bg-white/5 backdrop-blur-md rounded-[4rem] p-16 md:p-24 border border-white/10 max-w-2xl mx-auto shadow-2xl relative overflow-hidden"
                    >
                        <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent pointer-events-none" />
                        <div className="bg-amber-500/10 p-6 rounded-full w-fit mx-auto mb-8 text-amber-500 border border-amber-500/20">
                            <Lock size={60} className="animate-pulse" />
                        </div>
                        <h2 className="text-3xl font-black text-white uppercase tracking-tight mb-4">
                            Assistant Locked 🔒
                        </h2>
                        <p className="text-blue-100/50 font-bold mb-12 text-lg leading-relaxed">
                            The AI Packing Assistant is only available for **confirmed bookings**.<br />
                            Please make a booking and complete your payment to unlock your customized checklist.
                        </p>
                        <button
                            onClick={() => navigate("/app/dashboard")}
                            className="px-12 py-6 bg-white text-indigo-950 font-black text-xs uppercase tracking-[0.2em] rounded-3xl hover:bg-yellow-400 transition-all duration-300 shadow-2xl hover:scale-105 active:scale-95"
                        >
                            Discover Places
                        </button>
                    </motion.div>
                ) : (
                    <>
                        {/* CURRENT EXPEDITION SUMMARY BAR */}
                        {selectedBooking && (
                            <div className="mb-10 bg-white rounded-3xl p-6 md:p-8 shadow-xl border border-gray-50 flex flex-wrap justify-between items-center gap-6 print:border-gray-200 print:shadow-none print:mb-6">
                                <div className="flex flex-wrap gap-8 items-center">
                                    <div>
                                        <p className="text-[9px] text-gray-400 font-black uppercase tracking-widest mb-1.5">Destination</p>
                                        <h3 className="text-xl font-black text-indigo-950 uppercase tracking-tight flex items-center gap-2">
                                            <MapPin size={18} className="text-indigo-600 print:hidden" /> {selectedBooking.destination}
                                        </h3>
                                    </div>
                                    <div className="w-px h-10 bg-gray-100 hidden md:block print:hidden" />
                                    <div>
                                        <p className="text-[9px] text-gray-400 font-black uppercase tracking-widest mb-1.5">Departure</p>
                                        <p className="font-black text-gray-700 text-sm tracking-tight flex items-center gap-2">
                                            <Calendar size={16} className="text-indigo-600 print:hidden" /> {new Date(selectedBooking.startDate).toDateString()}
                                        </p>
                                    </div>
                                    <div className="w-px h-10 bg-gray-100 hidden md:block print:hidden" />
                                    <div>
                                        <p className="text-[9px] text-gray-400 font-black uppercase tracking-widest mb-1.5">Manifest Size</p>
                                        <p className="font-black text-gray-700 text-sm tracking-tight flex items-center gap-2">
                                            <Users size={16} className="text-indigo-600 print:hidden" /> {selectedBooking.travelers} Guest(s)
                                        </p>
                                    </div>
                                </div>

                                {/* Checklist Sync Status / Print Controls - Hidden in print */}
                                <div className="flex gap-3 print:hidden">
                                    <button
                                        onClick={() => window.print()}
                                        title="Print packing checklist"
                                        className="p-4 bg-gray-50 hover:bg-gray-100 text-indigo-950 rounded-2xl border border-gray-100 transition hover:-translate-y-0.5 active:scale-95 shadow-sm"
                                    >
                                        <Printer size={18} />
                                    </button>
                                    <button
                                        onClick={handleResetChecklist}
                                        title="Reset packed items"
                                        className="p-4 bg-gray-50 hover:bg-gray-100 text-indigo-950 rounded-2xl border border-gray-100 transition hover:-translate-y-0.5 active:scale-95 shadow-sm"
                                    >
                                        <RotateCcw size={18} />
                                    </button>
                                    <button
                                        onClick={() => setRegenerateConfirm(true)}
                                        title="Regenerate list using AI"
                                        className="p-4 bg-indigo-50 hover:bg-indigo-100 text-indigo-600 rounded-2xl border border-indigo-100/50 transition hover:-translate-y-0.5 active:scale-95 shadow-sm flex items-center gap-2 font-black text-[10px] uppercase tracking-wider px-5"
                                    >
                                        <RefreshCw size={14} className="animate-spin-hover" /> AI Regenerate
                                    </button>
                                </div>
                            </div>
                        )}

                        {/* LOADING SCREEN DURING AI LIST GENERATION */}
                        <AnimatePresence mode="wait">
                            {generatingList ? (
                                <motion.div
                                    key="generator"
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -20 }}
                                    className="bg-white rounded-[3rem] p-12 md:p-24 shadow-2xl border border-gray-50 flex flex-col items-center justify-center min-h-[50vh] text-center"
                                >
                                    <div className="relative mb-10">
                                        <div className="w-28 h-28 bg-indigo-50 rounded-full flex items-center justify-center border border-indigo-100">
                                            <Briefcase className="w-12 h-12 text-indigo-600 animate-bounce" />
                                        </div>
                                        <Sparkles className="w-8 h-8 text-amber-400 absolute -top-1 -right-1 animate-pulse" />
                                    </div>
                                    <h2 className="text-2xl md:text-3xl font-black text-indigo-950 uppercase tracking-tighter mb-4 flex items-center gap-3">
                                        AI Agent Assembling Baggage Log
                                    </h2>
                                    <p className="text-gray-400 font-bold uppercase tracking-widest text-xs animate-pulse">
                                        {loadingMessage}
                                    </p>
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="checklist"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    className="grid grid-cols-1 lg:grid-cols-3 gap-10 print:grid-cols-1"
                                >
                                    {/* PROGRESS AND INFO CARD */}
                                    <div className="lg:col-span-1 space-y-8 print:hidden">
                                        <div className="bg-white rounded-[2.5rem] p-8 shadow-xl border border-gray-50 relative overflow-hidden flex flex-col items-center text-center">
                                            <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent pointer-events-none" />
                                            
                                            <h3 className="font-black text-indigo-950 uppercase tracking-wider text-xs mb-8">Packing Progress</h3>

                                            {/* Circular Progress (SVG) */}
                                            <div className="relative w-44 h-44 flex items-center justify-center mb-8">
                                                <svg className="w-full h-full transform -rotate-90">
                                                    <circle
                                                        cx="88"
                                                        cy="88"
                                                        r="78"
                                                        stroke="#f3f4f6"
                                                        strokeWidth="12"
                                                        fill="transparent"
                                                    />
                                                    <circle
                                                        cx="88"
                                                        cy="88"
                                                        r="78"
                                                        stroke="#4f46e5"
                                                        strokeWidth="12"
                                                        fill="transparent"
                                                        strokeDasharray={490}
                                                        strokeDashoffset={490 - (490 * progressPercent) / 100}
                                                        className="transition-all duration-700 ease-out"
                                                    />
                                                </svg>
                                                <div className="absolute flex flex-col items-center">
                                                    <span className="text-4xl font-black text-indigo-950 tracking-tighter">{progressPercent}%</span>
                                                    <span className="text-[9px] text-gray-400 font-black uppercase tracking-widest mt-1">Packed</span>
                                                </div>
                                            </div>

                                            <p className="text-sm font-bold text-gray-600 mb-4 uppercase tracking-tight">
                                                {packedItemsCount} of {totalItemsCount} items completed
                                            </p>

                                            {progressPercent === 100 && totalItemsCount > 0 ? (
                                                <div className="bg-emerald-50 text-emerald-600 font-black text-[10px] uppercase tracking-widest px-6 py-3 rounded-xl border border-emerald-100 flex items-center gap-2 animate-bounce">
                                                    <CheckCircle size={14} /> Ready for departure!
                                                </div>
                                            ) : (
                                                <p className="text-xs text-gray-400 font-medium leading-relaxed max-w-[200px]">
                                                    {saving ? "Saving status to cloud..." : "All changes are automatically synchronized."}
                                                </p>
                                            )}
                                        </div>

                                        {/* EXPEDITION TIPS */}
                                        <div className="bg-gradient-to-br from-indigo-950 to-indigo-900 text-white rounded-[2.5rem] p-8 border border-white/10 shadow-2xl relative overflow-hidden">
                                            <div className="absolute -right-16 -bottom-16 w-44 h-44 bg-indigo-600/20 rounded-full blur-3xl pointer-events-none" />
                                            <Sparkles size={24} className="text-yellow-400 mb-6" />
                                            <h4 className="font-black uppercase tracking-wider text-xs mb-3 text-white">Traveler Tips</h4>
                                            <ul className="text-xs text-blue-100/60 font-medium space-y-4 text-left leading-relaxed">
                                                <li>• Check weather updates 24 hours before your departure date.</li>
                                                <li>• Keep physical copies of important documents in a waterproof pouch.</li>
                                                <li>• Tag your baggage clearly with your name and reference passport number.</li>
                                            </ul>
                                        </div>
                                    </div>

                                    {/* PRINT ONLY HEADER */}
                                    <div className="hidden print:block border-b-2 border-gray-300 pb-6 mb-6">
                                        <h2 className="text-2xl font-bold uppercase">{selectedBooking.destination} Packing Checklist</h2>
                                        <p className="text-sm text-gray-600 mt-2">
                                            Departure: {new Date(selectedBooking.startDate).toDateString()} | Duration: {Math.max(1, Math.ceil((new Date(selectedBooking.endDate) - new Date(selectedBooking.startDate)) / (1000 * 60 * 60 * 24)))} Days | Guests: {selectedBooking.travelers}
                                        </p>
                                    </div>

                                    {/* CHECKLIST CHECKBOXES */}
                                    <div className="lg:col-span-2 space-y-10 print:col-span-1 print:space-y-6">
                                        {packingList.map((cat, catIdx) => (
                                            <div key={catIdx} className="bg-white rounded-[2rem] p-8 shadow-lg border border-gray-50 flex flex-col print:border-none print:shadow-none print:p-0 print:mb-4">
                                                <div className="flex justify-between items-center mb-6 pb-4 border-b border-gray-50 print:border-b-2 print:border-gray-200 print:mb-2 print:pb-1">
                                                    <h3 className="font-black text-indigo-950 uppercase tracking-wide text-sm flex items-center gap-2 print:text-black print:text-base">
                                                        <span className="w-2.5 h-2.5 rounded-full bg-indigo-600 print:hidden" /> {cat.category}
                                                    </h3>
                                                    <span className="text-[10px] text-gray-400 font-black uppercase tracking-wider print:text-gray-600">
                                                        {cat.items.filter(i => i.packed).length} / {cat.items.length} Checked
                                                    </span>
                                                </div>

                                                {/* ITEMS LIST */}
                                                <div className="space-y-3 mb-6 print:space-y-1 print:mb-0">
                                                    {cat.items.map((item, itemIdx) => (
                                                        <div 
                                                            key={itemIdx} 
                                                            className={`flex justify-between items-center p-4 rounded-2xl border transition group/item print:border-none print:p-1.5
                                                                ${item.packed 
                                                                    ? 'bg-gray-50/50 border-gray-100 text-gray-400' 
                                                                    : 'bg-white border-gray-100 text-indigo-950 hover:bg-indigo-50/20'
                                                                }
                                                            `}
                                                        >
                                                            <div className="flex items-center gap-4 cursor-pointer flex-1" onClick={() => handleTogglePacked(catIdx, itemIdx)}>
                                                                {/* Custom Checkbox (Hidden in Print) */}
                                                                <div className={`w-6 h-6 rounded-lg border flex items-center justify-center shrink-0 transition print:hidden
                                                                    ${item.packed 
                                                                        ? 'bg-indigo-600 border-indigo-600 text-white' 
                                                                        : 'bg-white border-gray-300'
                                                                    }
                                                                `}>
                                                                    {item.packed && <Check size={14} className="stroke-[3]" />}
                                                                </div>
                                                                {/* Print Checkbox (Visible in Print Only) */}
                                                                <div className="hidden print:block w-4 h-4 border border-black mr-2 shrink-0" />

                                                                <span className={`text-sm font-semibold tracking-tight leading-none capitalize print:text-black print:text-sm
                                                                    ${item.packed ? 'line-through decoration-indigo-400 decoration-2' : ''}
                                                                `}>
                                                                    {item.name}
                                                                </span>

                                                                {/* Custom Item Badge */}
                                                                {item.custom && (
                                                                    <span className="bg-indigo-50 text-indigo-600 font-bold text-[8px] px-2 py-0.5 rounded uppercase tracking-wider print:hidden">
                                                                        Custom
                                                                    </span>
                                                                )}
                                                            </div>

                                                            {/* Trash Button - Hidden in Print */}
                                                            <button
                                                                onClick={() => handleDeleteItem(catIdx, itemIdx, item.name)}
                                                                className="opacity-0 group-hover/item:opacity-100 p-2 bg-rose-50 text-rose-500 rounded-lg hover:bg-rose-500 hover:text-white transition shadow-sm border border-rose-100 cursor-pointer print:hidden"
                                                            >
                                                                <Trash2 size={12} />
                                                            </button>
                                                        </div>
                                                    ))}

                                                    {cat.items.length === 0 && (
                                                        <p className="text-xs text-gray-400 font-medium italic text-center py-4">No items in this category.</p>
                                                    )}
                                                </div>

                                                {/* ADD ITEM INPUT - Hidden in Print */}
                                                <form
                                                    onSubmit={(e) => {
                                                        e.preventDefault();
                                                        handleAddItem(catIdx, cat.category);
                                                    }}
                                                    className="flex gap-2 mt-auto print:hidden"
                                                >
                                                    <input
                                                        type="text"
                                                        value={newItemText[cat.category] || ""}
                                                        onChange={(e) => setNewItemText(prev => ({ ...prev, [cat.category]: e.target.value }))}
                                                        placeholder={`Add item to ${cat.category}...`}
                                                        className="flex-1 bg-gray-50 border border-gray-100 rounded-xl px-4 py-2.5 text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500 text-indigo-950 font-semibold"
                                                    />
                                                    <button
                                                        type="submit"
                                                        disabled={!newItemText[cat.category]?.trim()}
                                                        className="bg-indigo-600 hover:bg-indigo-700 text-white p-2.5 rounded-xl transition disabled:opacity-40 disabled:cursor-not-allowed shadow-md cursor-pointer flex items-center justify-center"
                                                    >
                                                        <Plus size={18} />
                                                    </button>
                                                </form>
                                            </div>
                                        ))}
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </>
                )}

                {/* REGENERATE CHECKLIST CONFIRMATION MODAL */}
                <AnimatePresence>
                    {regenerateConfirm && (
                        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
                            {/* Backdrop */}
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                onClick={() => setRegenerateConfirm(false)}
                                className="absolute inset-0 bg-indigo-950/40 backdrop-blur-sm"
                            />
                            {/* Modal Card */}
                            <motion.div
                                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                                animate={{ opacity: 1, scale: 1, y: 0 }}
                                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                                className="bg-white rounded-[2.5rem] p-8 md:p-10 max-w-md w-full border border-gray-100 shadow-2xl relative z-10 text-center"
                            >
                                <div className="bg-amber-50 text-amber-600 p-4 rounded-full w-fit mx-auto mb-6 border border-amber-100">
                                    <ShieldAlert size={36} />
                                </div>
                                <h3 className="font-black text-indigo-950 uppercase tracking-tight text-xl mb-3">Regenerate Checklist?</h3>
                                <p className="text-sm text-gray-500 font-medium leading-relaxed mb-8">
                                    This will clear your current progress and custom items added. Our AI will assemble a brand new checklist based on your booking details.
                                </p>
                                <div className="flex gap-4">
                                    <button
                                        onClick={() => setRegenerateConfirm(false)}
                                        className="flex-1 py-4 bg-gray-50 text-indigo-950 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-gray-100 transition border border-gray-100 cursor-pointer"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        onClick={() => loadPackingList(selectedBooking._id, true)}
                                        className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-indigo-700 transition shadow-lg shadow-indigo-100 cursor-pointer"
                                    >
                                        Yes, Regenerate
                                    </button>
                                </div>
                            </motion.div>
                        </div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
